#!/bin/bash

ln -sf ~/dotfiles/bashrc ~/.bashrc
ln -sf ~/dotfiles/xinitrc ~/.xinitrc

mkdir -p $HOME/.vim
ln -sf ~/dotfiles/vimrc ~/.vim/vimrc

mkdir -p $HOME/.config/emacs
ln -sf ~/dotfiles/init.el ~/.config/emacs/init.el
