#!/bin/bash

ln -sf ~/dotfiles/.bashrc ~/
ln -sf ~/dotfiles/.xinitrc ~/
ln -sf ~/dotfiles/.vimrc ~/
ln -sf ~/dotfiles/.emacs ~/

cd dwm/ && sudo make clean install
cd ..

cd st/ && sudo make clean install
cd ..

cd dmenu/ && sudo make clean install
cd ..
