source $VIMRUNTIME/defaults.vim

set viminfofile=~/dotfiles/.vim/viminfo
set background=dark
set number
set relativenumber
set cursorline
set hlsearch
set ignorecase
set smartcase

colorscheme retrobox
